### ISSUE TITLE
[Bug report] First two jobs are rared/pared in parallel

### ISSUE THREAD

**Issue by Tensai75** [mbruel/ngPost#56]
If PREPARE_PACKING option is enabled and if the monitored folder is empty, when two folders/jobs are moved to it simultaneously, ngPost will start to rar/par both. This is not the intended behavior. At the same time only one post should be rared/pared. Rar/par of the second job should only start if first job is already uploading.

Regards, Tensai

**Comment by mbruel** [comment]
hum ok, yeah maybe, I think I had the same behaviour with the --auto mode.
I'll try to fix it when I've some time, probably next week.

**Comment by mbruel** [comment]
@Tensai75 it should be fixed, can you please confirm and if all good close this issue.
I've tested only the auto mode but should work also in monitor.
[Here is a compiled version for win64](https://files.fm/u/qzfc5djk), just replace the exe.

**Comment by Tensai75** [comment]
Fixed with commit 38e1f69ec75c07611f9d038b2d93c924d5fa2dcc

Thanks man!

**Comment by Tensai75** [comment]
Hi Matthieu

in some circumstances, simultaneous rar/par of two jobs still happens in monitor folder mode, e.g. if in the queue a rather small upload is followed by a very large upload and then by a third upload. 

Add the following upload jobs to the monitored folder shortly one after the other:
1. a small upload (e.g. one mp3 file)-> job No. 1
2. a very large upload (e.g. a BD) -> job No. 2 
3. any other upload (size doesn't matter) -> job No. 3

Job No. 2 must be enough large so it is still being rared/pared while job No. 1 has already finished uploading.

### Expected behavior:
1. ngPost starts to rar/par the job No. 1.
2. ngPost starts to rar/par the job No. 2 as soon as job No. 1 has finished rar/par and is uploading.
3. ngPost starts to rar/par the job No. 3 as soon as job No. 2 has finished rar/par and is uploading.

### Actual behavior:
1. ngPost starts to rar/par the job No. 1.
2. ngPost starts to rar/par job No. 2 as soon as job No. 1 has finished rar/par and is uploading.
3. ngPost starts to rar/par job No. 3 as soon as job No. 1 has finished uploading although job No. 2 is still raring/paring

Hope I was able to explain it enough clearly.

Regards, Tensai

**Comment by mbruel** [comment]
what about now? 
I didn't test but in theory the change should do the job ;)
Here is [the win64 binary](https://files.fm/u/xajqjawd)

**Comment by noobcoder1983** [comment]
mbruel could you add this option "PREPARE_PACKING" and other new features to the config/readme file?

Is this feature in the new 4.8 version and bugfixed?

Thanks a lot!

Regards

**Comment by mbruel** [comment]
it's in the readme: " it packs the next Post while uploading the current one (compression + par2 generation)"
and [in the config file](https://github.com/mbruel/ngPost/blob/6e9fe8d23df31a0b1e79d541a7888da9827d17ea/ngPost.conf#L106)...

there is a bug in the v4.8 that Tensai raised. The fix will only be included in the v4.9 which I'll release asap when I've the confirmation the bug is properly fixed.
@Tensai75 please let me know if you still find issue with my latest commit.
Cheers

**Comment by noobcoder1983** [comment]
Oh ok sorry thanks for the info and the quick bugfixing.

Is it possible to program a function/feature that broken uploads can be resumed?

**Comment by Tensai75** [comment]
Hi Matthieu 

first tests seem to confirm that parallel rar/par jobs are no longer occurring.
I will therefore close this issue again.

Again many thanks, mate!

Regards, Tensai

**Comment by mbruel** [comment]
@Tensai75 cool good news :)
I'll probably build the v4.9 with that fix sometime this week.
I'll see if I include sth else with it. Not sure what I could do rapidly...
